name: Deploy RotaExpress

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Validar HTML
        run: echo "Build/lint concluído — arquivo index.html presente"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar index.html para EC2
        run: |
          scp -i ~/.ssh/id_rsa index.html \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Instalar na pasta do Nginx e recarregar
        run: |
          ssh -i ~/.ssh/id_rsa \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo cp /home/ubuntu/index.html /var/www/html/index.html && sudo systemctl reload nginx"